### ISSUE TITLE
quote variants

### ISSUE THREAD

**Issue by manalishi79** [Financial-Times/o-quote#4]
Standard quote

Kevin Wilson - version to be used with a headshot (could disappear on smallscreen)

Stat quote version like BBC

UK GDP per capita
38,514

or

Rise in UK
employment
2.1%
in 2013 Q4

**Comment by onishiweb** [comment]
Is there any update on this. Have any more quote variants been added to Next that could be brought across to the Origami component?

**Comment by AlbertoElias** [comment]
There are quote designs on Next, yes
